-- CRIAÇÃO TABELA SAC
CREATE TABLE T_MC_SGV_SAC (
    NR_CHAMADO NUMBER(10) GENERATED ALWAYS AS IDENTITY,
    CD_FUNCIONARIO NUMBER(10) NOT NULL,
    CD_PRODUTO NUMBER(10) NOT NULL,
    NR_CLIENTE NUMBER(5) NOT NULL,
    DS_DETALHADA_CLIENTE VARCHAR2(4000) NOT NULL,
    DT_ABERTURA_CHAMADO DATE NOT NULL,
    DT_ATENDIMENTO DATE NULL,
    DT_MINUTOS_ATENDIMENTO DATE NOT NULL,
    NR_TEMPO_TOTAL_SAC NUMBER(10) NULL,
    DS_DETALHADA_RETORNO_SAC VARCHAR2(100) NULL,
    TP_CHAMADO CHAR(1) NOT NULL,
    ST_CHAMADO CHAR(1) NOT NULL,
    NR_INDICE_SATISFACAO NUMBER(2) NULL
);

    ALTER TABLE T_MC_SGV_SAC ADD CONSTRAINT PK_MC_SGV_SAC PRIMARY KEY (NR_CHAMADO);

    ALTER TABLE T_MC_SGV_SAC ADD CONSTRAINT CK_MC_SGV_SAC_TP_CHAMADO CHECK (TP_CHAMADO IN ('1' , '2'));
    
    ALTER TABLE T_MC_SGV_SAC ADD CONSTRAINT CK_MC_SGV_SAC_ST_CHAMADO CHECK (ST_CHAMADO IN ('E' , 'C', 'F' , 'X'));
    
    ALTER TABLE T_MC_SGV_SAC ADD CONSTRAINT CK_MC_SGV_SAC_NR_INDICE_SATISFACAO CHECK (NR_INDICE_SATISFACAO BETWEEN 1 AND 10);
    
-- CRIAÇÃO TABELA FUNCIONÁRIO

CREATE TABLE T_MC_FUNCIONARIO (
    CD_FUNCIONARIO NUMBER(10) NOT NULL,
    CD_COORDENADOR NUMBER(10) NOT NULL,
    CD_DEPTO NUMBER(3) NOT NULL,
    NM_FUNCIONARIO VARCHAR2(160) NOT NULL,
    NR_CPF NUMBER(11) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    NM_TELEFONE NUMBER(11) NOT NULL,
    DS_EMAIL VARCHAR2(80) NOT NULL,
    DS_CARGO VARCHAR2(80) NOT NULL,
    VL_SALARIO NUMBER(10,2) NULL,
    ST_FUNC CHAR(1) NULL,
    DT_CADASTRAMENTO DATE NULL,
    DT_DESLIGAMENTO DATE NULL
);

    ALTER TABLE T_MC_FUNCIONARIO
ADD CONSTRAINT PK_MC_FUNCIONARIO
    PRIMARY KEY (CD_FUNCIONARIO);
    
    ALTER TABLE T_MC_FUNCIONARIO
ADD CONSTRAINT UN_MC_NR_CPF
    UNIQUE (NR_CPF);
    
-- CRIAÇÃO TABELA ENDEREÇO FUNCIONÁRIO

CREATE TABLE T_MC_END_FUNC (
    CD_LOGRADOURO NUMBER(10) NOT NULL,
    CD_FUNCIONARIO NUMBER(10) NOT NULL,
    NR_END NUMBER(8) NOT NULL,
    DS_COMPLEMENTO_END VARCHAR2(80) NULL,
    DT_INICIO DATE NOT NULL,
    DT_TERMINO DATE NULL,
    ST_END CHAR(1) NOT NULL
);

    ALTER TABLE T_MC_END_FUNC
ADD CONSTRAINT PK_MC_END_FUNC
    PRIMARY KEY (CD_LOGRADOURO);
    
-- CRIAÇÃO TABELA DEPARTAMENTO

CREATE TABLE T_MC_DEPTO (
    CD_DEPTO NUMBER(3) NOT NULL,
    NM_DEPTO VARCHAR2(100) NOT NULL,
    ST_DEPTO CHAR(1) NOT NULL
);

    ALTER TABLE T_MC_DEPTO
ADD CONSTRAINT PK_MC_DEPTO
    PRIMARY KEY (CD_DEPTO);
    
-- CRIAÇÃO TABELA CLIENTE

CREATE TABLE T_MC_CLIENTE (
    nr_cliente NUMBER(5) NOT NULL,
    nm_cliente VARCHAR2(160) NOT NULL,
    st_client CHAR(1) NOT NULL,
    dt_nasc DATE NOT NULL,
    nm_login VARCHAR2(50),
    ds_senha VARCHAR2(50),
    fl_sexo_biologico VARCHAR2(50) NOT NULL,
    qt_estrelas NUMBER(1),
    nr_telefone VARCHAR2(20),
    ds_genero VARCHAR2(50)
);

ALTER TABLE T_MC_CLIENTE 
ADD CONSTRAINT PK_T_MC_CLIENTE
PRIMARY KEY (NR_CLIENTE);

--CRIAÇÃO TABELA CLIENTE PF

ALTER TABLE T_MC_CLI_FISICA 
ADD CONSTRAINT PK_T_MC_CLI_FISICA
PRIMARY KEY (NR_CLIENTE);

--CRIAÇÃO TABELA PJ

CREATE TABLE T_MC_CLI_JURIDICA (
nr_cliente number not null,
dt_fundacao date,
nrcnpj varchar2(20),
nr_inscr_est varchar2(15)
);

ALTER TABLE T_MC_CLI_JURIDICA 
ADD CONSTRAINT PK_MC_T_CLI_JURIDICA
PRIMARY KEY (NR_CLIENTE);

-- CRIAÇÃO TABELA VISUALIZAÇÃO VIDEO

CREATE TABLE T_MC_VISUALIZACAO_VIDEO (
cd_visualizacao number (7) not null,
cd_video number (4)not null,
cd_produto number(10)not null,
nr_cliente number(5),
st_visualização date
);

ALTER TABLE T_MC_VISUALIZACAO_VIDEO
ADD CONSTRAINT PK_MC_VISUALIZACAO_VIDEO
PRIMARY KEY (CD_VISUALIZACAO);

-- CRIAÇÃO TABELA VÍDEO PRODUTO

CREATE TABLE t_mc_video_produto(
    cd_video NUMBER(4) NOT NULL, 
    cd_produto NUMBER(10) NOT NULL, --ok
    cd_categoria_video NUMBER(4) NOT NULL, --ok
    dt_cadastro DATE NOT NULL,
    st_video CHAR(1) NOT NULL
);

ALTER TABLE t_mc_video_produto ADD CONSTRAINT pk_mc_video_produto PRIMARY KEY ( cd_video );

-- CRIAÇÃO TABELA CATEGORIA VÍDEO

CREATE TABLE t_mc_categoria_video (
    cd_categoria_video NUMBER(4) NOT NULL,
    tp_video VARCHAR2(30) NOT NULL,
    ds_categoria VARCHAR2(50) NOT NULL,
    dt_inicio_categoria DATE NOT NULL,
    dt_termino_categoria DATE NULL,
    st_categoria CHAR(1) NOT NULL  
);

ALTER TABLE t_mc_categoria_video ADD CONSTRAINT pk_mc_categoria_video PRIMARY KEY ( cd_categoria_video );

ALTER TABLE t_mc_categoria_video ADD CONSTRAINT un_mc_categoria_video_categoria UNIQUE ( ds_categoria );

ALTER TABLE t_mc_categoria_video ADD CONSTRAINT ck_mc_categoria_video_st_categoria CHECK ( st_categoria IN ( 'A', 'I' ) );

-- CRIAÇÃO TABELA PRODUTO

CREATE TABLE t_mc_produto (
    cd_produto NUMBER(10) NOT NULL,
    cd_categoria_produto NUMBER(4) NOT NULL,
    ds_normal_produto VARCHAR2(80) NOT NULL,
    ds_completa_produto VARCHAR2(4000) NOT NULL,
    nr_cd_barras_produto VARCHAR2(50) NULL,
    vl_unitario NUMBER(8,2) NOT NULL,
    tp_embalagem VARCHAR2(15) NULL,
    st_produto CHAR(1) NOT NULL,
    vl_preco_lucro NUMBER(8,2) NULL
);

    ALTER TABLE t_mc_produto 
ADD CONSTRAINT pk_mc_produto   
    PRIMARY KEY ( cd_produto );

    ALTER TABLE t_mc_produto 
ADD CONSTRAINT un_mc_produto_normal_produto 
    UNIQUE ( ds_normal_produto );

    ALTER TABLE t_mc_produto
ADD CONSTRAINT ck_mc_produto_st_produto 
    CHECK ( st_produto IN ( 'A', 'I', 'P') );

    ALTER TABLE t_mc_video_produto
ADD CONSTRAINT ck_mc_video_produto_st_video 
    CHECK ( st_video IN ( 'A', 'I' ) );

-- CRIAÇÃO TABELA CATEGORIA PRODUTO

CREATE TABLE t_mc_categoria_produto (
    cd_categoria_produto NUMBER(4) NOT NULL,
    tp_video VARCHAR2(30) NOT NULL,
    ds_categoria VARCHAR2(50) NOT NULL,
    dt_inicio_categoria DATE NOT NULL,
    dt_termino_categoria DATE NULL,
    st_categoria CHAR(1) NOT NULL  
);

ALTER TABLE t_mc_categoria_produto ADD CONSTRAINT pk_mc_categoria_produto PRIMARY KEY (cd_categoria_produto);

ALTER TABLE t_mc_categoria_produto ADD CONSTRAINT un_mc_produto_categoria UNIQUE (ds_categoria);

ALTER TABLE t_mc_categoria_produto ADD CONSTRAINT ck_mc_categoria_produto_st_categoria check (ST_CATEGORIA IN ('A','I'));

-- CRIAÇÃO TABELA ESTADO

CREATE TABLE T_MC_ESTADO(
NM_ESTADO VARCHAR2(30) NOT NULL,
SG_ESTADO CHAR(2) NOT NULL);

ALTER TABLE T_MC_ESTADO ADD CONSTRAINT PK_MC_ESTADO PRIMARY KEY (SG_ESTADO);

-- CRIAÇÃO TABELA END CLIENTE

CREATE TABLE T_MC_END_CLI (
    NR_CLIENTE NUMBER(5) NOT NULL,
    CD_LOGRADOURO NUMBER(5) NOT NULL,
    NR_END NUMBER(8),
    DS_COMPLEMENTO_END VARCHAR2(80),
    DT_INICIO DATE,
    DT_TERMINO DATE,
    ST_END CHAR(1)
);

ALTER TABLE T_MC_END_CLI ADD CONSTRAINT PK_MC_END_CLI PRIMARY KEY (CD_LOGRADOURO, NR_CLIENTE);

-- CRIAÇÃO TABELA BAIRRO

    CREATE TABLE T_MC_BAIRRO (
    CD_BAIRRO NUMBER(8),
    CD_CIDADE NUMBER(8),
    NM_BAIRRO VARCHAR2(46),
    NM_ZONA_BAIRRO VARCHAR2(20)
);

ALTER TABLE T_MC_BAIRRO ADD CONSTRAINT PK_MC_BAIRRO PRIMARY KEY (CD_CIDADE);

-- CRIAÇÃO TABELA LOGRADOURO

CREATE TABLE t_mc_logradouro (
    cd_logradouro     NUMBER(10),
    cd_bairro         NUMBER(8),
    cd_logradouro_cli NUMBER(10),
    nr_cliente1       NUMBER(5),
    nm_logradouro     VARCHAR(160),
    nr_cep            NUMBER(8)
);

ALTER TABLE T_MC_LOGRADOURO ADD CONSTRAINT PK_MC_LOGRADOURO PRIMARY KEY (CD_LOGRADOURO);

--CRIAÇÃO TABELA CIDADE
CREATE TABLE mc_cidade (
    cd_cidade NUMBER(8),
    sg_estado CHAR(2),
    nm_cidade VARCHAR2(60),
    cd_ibge   NUMBER(8),
    nr_ddd    NUMBER(3)
);

ALTER TABLE mc_cidade ADD CONSTRAINT pk_mc_cidade PRIMARY KEY ( cd_cidade );

-- CRIAÇÃO CHAVES ESTRANGEIRAS TABELA SAC
    
    ALTER TABLE T_MC_SGV_SAC
ADD CONSTRAINT FK_MC_SGC_SAC_CLIENTE 
    FOREIGN KEY ( NR_CLIENTE )
    REFERENCES T_MC_CLIENTE ( NR_CLIENTE );
    
    ALTER TABLE T_MC_SGV_SAC
ADD CONSTRAINT FK_MC_SGC_SAC_FUNCIONARIO
    FOREIGN KEY (CD_FUNCIONARIO)
    REFERENCES T_MC_FUNCIONARIO (CD_FUNCIONARIO);

    ALTER TABLE T_MC_SGV_SAC
ADD CONSTRAINT FK_MC_SGC_SAC_PRODUTO
    FOREIGN KEY (CD_PRODUTO)
    REFERENCES T_MC_PRODUTO (CD_PRODUTO);

    
    ALTER TABLE T_MC_FUNCIONARIO
ADD CONSTRAINT FK_MC_FUNCIONARIO_DEPARTAMENTO
    FOREIGN KEY (CD_DEPTO)
    REFERENCES T_MC_DEPTO (CD_DEPTO);

    ALTER TABLE T_MC_FUNCIONARIO
ADD CONSTRAINT FK_MC_FUNCIONARIO_FUNCIONARIO
    FOREIGN KEY (CD_COORDENADOR)
    REFERENCES T_MC_FUNCIONARIO (CD_FUNCIONARIO);
    

    ALTER TABLE T_MC_END_FUNC
ADD CONSTRAINT FK_MC_END_FUNC_LOGRADOURO
    FOREIGN KEY (CD_LOGRADOURO)
    REFERENCES T_MC_LOGRADOURO (CD_LOGRADOURO);
    
    ALTER TABLE T_MC_END_FUNC
ADD CONSTRAINT FK_MC_END_FUNC_FUNCIONARIO
    FOREIGN KEY (CD_FUNCIONARIO)
    REFERENCES T_MC_FUNCIONARIO (CD_FUNCIONARIO);
       
    ALTER TABLE T_MC_CLI_FISICA 
ADD CONSTRAINT FK_MC_CLIENTE_FISICA
    FOREIGN KEY (NR_CLIENTE)
    REFERENCES T_MC_CLIENTE (NR_CLIENTE);

    ALTER TABLE T_MC_CLI_JURIDICA 
ADD CONSTRAINT FK_MC_CLIENTE_JURIDICA
    FOREIGN KEY (NR_CLIENTE)
    REFERENCES T_MC_CLIENTE (NR_CLIENTE);

    ALTER TABLE T_MC_VISUALIZACAO_VIDEO
ADD CONSTRAINT FK_MC_VISUALIZACAO_CLIENTE
    FOREIGN KEY (NR_CLIENTE)
    REFERENCES T_MC_CLIENTE (NR_CLIENTE);

    ALTER TABLE T_MC_VISUALIZACAO_VIDEO
ADD CONSTRAINT FK_MC_VISUALIZACAO_VIDEO_VIDEO_PRODUTO
    FOREIGN KEY (CD_VIDEO)
    REFERENCES T_MC_VIDEO_PRODUTO (CD_VIDEO);

    ALTER TABLE T_MC_VISUALIZACAO_VIDEO
ADD CONSTRAINT FK_MC_VISUALIZACAO_VIDEO_PRODUTO
    FOREIGN KEY (CD_PRODUTO)
    REFERENCES T_MC_PRODUTO (CD_PRODUTO);

    ALTER TABLE T_MC_VIDEO_PRODUTO 
ADD CONSTRAINT FK_MC_VIDEO_PRODUTO_CATEGORIA 
    FOREIGN KEY ( CD_CATEGORIA_VIDEO ) 
    REFERENCES T_MC_CATEGORIA_VIDEO (CD_CATEGORIA_VIDEO);

    ALTER TABLE T_MC_VIDEO_PRODUTO 
ADD CONSTRAINT FK_MC_VIDEO_PRODUTO_PRODUTO 
    FOREIGN KEY ( CD_PRODUTO ) 
    REFERENCES T_MC_PRODUTO (CD_PRODUTO); 

    ALTER TABLE T_MC_PRODUTO 
ADD CONSTRAINT FK_MC_PRODUTO_CATEGORIA_PRODUTO 
    FOREIGN KEY ( CD_CATEGORIA_PRODUTO ) 
    REFERENCES T_MC_CATEGORIA_PRODUTO (CD_CATEGORIA_PRODUTO);

    ALTER TABLE MC_ESTADO 
ADD CONSTRAINT FK_MC_END_CLI 
    FOREIGN KEY (NR_CLEINTE) 
    REFERENCES MC_CLIENTE (NR_CLIENTE);
    
    ALTER TABLE MC_ESTADO 
ADD CONSTRAINT FK_MC_CIDADE 
    FOREIGN KEY (SG_ESTADO) 
    REFERENCES MC_ESTADO (SG_ESTADO);
    
    ALTER TABLE mc_logradouro
ADD CONSTRAINT fk_mc_logradouro_bairro 
    FOREIGN KEY ( cd_bairro )
    REFERENCES mc_bairro ( cd_bairro );

    ALTER TABLE MC_LOGRADOURO 
ADD CONSTRAINT FK_MC_LOGRADOURO_CLIENTE 
    FOREIGN KEY (CD_LOGRADOURO, NR_CLIENTE) 
    REFERENCES MC_CLIENTE (NR_CLIENTE);

    ALTER TABLE MC_CIDADE 
ADD CONSTRAINT FK_MC_CIDADE 
    FOREIGN KEY (SG_ESTADO) 
    REFERENCES MC_ESTADO (SG_ESTADO);